#!/bin/bash
# Obsolete: instances now run as systemd user services.
# See README.md ("Run as systemd user services").
systemctl --user status rssfeed@slashdot rssfeed@newscz rssfeed@longreads rssfeed-brmlab
